services:
  - type: web
    name: quizwar
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/quizwar/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
